version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-auto-committer
    restart: unless-stopped
    ports:
      - '3339:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm run start:prod && tail -f /dev/null"
