version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-auto-committer
    user: '${UID}:${GID}'
    restart: unless-stopped
    ports:
      - '3339:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.ssh:/root/.ssh:ro
      - .ssh:/app/.ssh
    environment:
      - NODE_ENV=production
      - GIT_EMAIL=adrielcolherinhas@gmail.com
      - GIT_NAME=adrielCastejon
